### ISSUE TITLE
AppVeyor build failure

### ISSUE THREAD

**Issue by jnothman** [MacPython/scikit-learn-wheels#9]
```
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\lib\site-packages\wheelhouse_uploader\__main__.py", line 3, in <module>
    main()
  File "C:\Python27\lib\site-packages\wheelhouse_uploader\commandline.py", line 123, in main
    return handle_upload(options)
  File "C:\Python27\lib\site-packages\wheelhouse_uploader\commandline.py", line 106, in handle_upload
    uploader.upload(options.local_folder, options.container_name)
  File "C:\Python27\lib\site-packages\wheelhouse_uploader\upload.py", line 57, in upload
    retry_on_error=retry_on_error - 1)
  File "C:\Python27\lib\site-packages\wheelhouse_uploader\upload.py", line 57, in upload
    retry_on_error=retry_on_error - 1)
  File "C:\Python27\lib\site-packages\wheelhouse_uploader\upload.py", line 57, in upload
    retry_on_error=retry_on_error - 1)
  File "C:\Python27\lib\site-packages\wheelhouse_uploader\upload.py", line 46, in upload
    return self._try_upload_once(local_folder, container)
  File "C:\Python27\lib\site-packages\wheelhouse_uploader\upload.py", line 67, in _try_upload_once
    filepaths, local_metadata = self._scan_local_files(local_folder)
  File "C:\Python27\lib\site-packages\wheelhouse_uploader\upload.py", line 200, in _scan_local_files
    for filename in sorted(os.listdir(local_folder)):
WindowsError: [Error 3] The system cannot find the path specified: 'dist\\*.*'
```

What's going on?

**Comment by matthew-brett** [comment]
Is the command running from the correct directory?  Does `dist` exist, in fact?  Test with `dir dist\\*.*` as a debug line?

**Comment by amueller** [comment]
wait that worked before though, right? Is that related to you removing the folder? hm...

**Comment by amueller** [comment]
possible fix in b9616d21b1420dd4c98fcc0ad4af8076360be6df

**Comment by amueller** [comment]
looks like it's working....
